{
  parserClass="io.github.grigala.plugins.ruta.language.parser.RutaParser.kt"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ruta"
  psiImplClassSuffix="Impl"
  psiPackage="io.github.grigala.plugins.ruta.language.psi"
  psiImplPackage="io.github.grigala.plugins.ruta.language.impl"

  elementTypeHolderClass="io.github.grigala.plugins.ruta.language.psi.RutaTypes"
  elementTypeClass="io.github.grigala.plugins.ruta.language.psi.RutaElementType"
  tokenTypeClass="io.github.grigala.plugins.ruta.language.psi.RutaTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY
